### ISSUE TITLE
Add fileUp button to master branch

### ISSUE THREAD

**Issue by tmp-me** [NRGI/pdf-scraper#6]
![image](https://user-images.githubusercontent.com/44948663/48315807-29ff5d00-e5db-11e8-8931-52cfb00ad576.png)

In the current Readme I found the documentation, that the application now includes the Upload File button. I assume it is not commited in the ui.R. Would be great to have it!

Br, Malte

**Comment by t-morrison** [comment]
@tmp-me you are correct, the online app is a few commits behind this repo. I will update asap.
